// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class CategoryMaster
{
    public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Slug { get; set; }

    public virtual ICollection<MangaSeries> Series { get; set; } = new List<MangaSeries>();
}