// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class ContractMasterThinhPh
{
    public int ContractIdThinhPh { get; set; }

    public int SeriesId { get; set; }

    public DateTime? SignDate { get; set; }

    public decimal BaseRoyaltyRate { get; set; }

    public string ContractTerms { get; set; }

    public bool? IsExclusive { get; set; }

    public virtual ICollection<ContractAssetThinhPh> ContractAssetThinhPhs { get; set; } = new List<ContractAssetThinhPh>();

    public virtual ICollection<RoyaltyPaymentThinhPh> RoyaltyPaymentThinhPhs { get; set; } = new List<RoyaltyPaymentThinhPh>();

    public virtual MangaSeries Series { get; set; }
}