// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Manga.Entites.ThinhPH.Models;

public partial class MangaFlow_ProContext : DbContext
{
    public MangaFlow_ProContext()
    {

    }
    public MangaFlow_ProContext(DbContextOptions<MangaFlow_ProContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }

    public virtual DbSet<ContractAssetThinhPh> ContractAssetThinhPhs { get; set; }

    public virtual DbSet<ContractMasterThinhPh> ContractMasterThinhPhs { get; set; }

    public virtual DbSet<MangaChapter> MangaChapters { get; set; }

    public virtual DbSet<MangaSeries> MangaSeries { get; set; }

    public virtual DbSet<MangaStatistic> MangaStatistics { get; set; }

    public virtual DbSet<ManuscriptAnnotation> ManuscriptAnnotations { get; set; }

    public virtual DbSet<ManuscriptPage> ManuscriptPages { get; set; }

    public virtual DbSet<ManuscriptVersion> ManuscriptVersions { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<RoyaltyPaymentThinhPh> RoyaltyPaymentThinhPhs { get; set; }

    public virtual DbSet<SeriesCollection> SeriesCollections { get; set; }

    public virtual DbSet<SystemUserAccount> SystemUserAccounts { get; set; }

    public virtual DbSet<TaskAssignment> TaskAssignments { get; set; }

    public virtual DbSet<TaskReview> TaskReviews { get; set; }

    public virtual DbSet<TaskSubmission> TaskSubmissions { get; set; }

    public virtual DbSet<UserActivityLog> UserActivityLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CategoryMaster>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Category__19093A2BD644C58C");

            entity.ToTable("Category_Master");

            entity.HasIndex(e => e.Slug, "UQ__Category__BC7B5FB6F064B7FF").IsUnique();

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Slug)
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<ContractAssetThinhPh>(entity =>
        {
            entity.HasKey(e => e.AssetIdThinhPh).HasName("PK__Contract__4349237286BD27AC");

            entity.ToTable("Contract_Asset_ThinhPH");

            entity.Property(e => e.AssetIdThinhPh).HasColumnName("AssetID_ThinhPH");
            entity.Property(e => e.ContractIdThinhPh).HasColumnName("ContractID_ThinhPH");
            entity.Property(e => e.FileUrl)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UploadedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.ContractIdThinhPhNavigation).WithMany(p => p.ContractAssetThinhPhs)
                .HasForeignKey(d => d.ContractIdThinhPh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract___Contr__7A672E12");
        });

        modelBuilder.Entity<ContractMasterThinhPh>(entity =>
        {
            entity.HasKey(e => e.ContractIdThinhPh).HasName("PK__Contract__C90D3409B95F21CD");

            entity.ToTable("Contract_Master_ThinhPH");

            entity.Property(e => e.ContractIdThinhPh).HasColumnName("ContractID_ThinhPH");
            entity.Property(e => e.BaseRoyaltyRate).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.IsExclusive).HasDefaultValue(true);
            entity.Property(e => e.SeriesId).HasColumnName("SeriesID");
            entity.Property(e => e.SignDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");

            entity.HasOne(d => d.Series).WithMany(p => p.ContractMasterThinhPhs)
                .HasForeignKey(d => d.SeriesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Contract___Serie__71D1E811");
        });

        modelBuilder.Entity<MangaChapter>(entity =>
        {
            entity.HasKey(e => e.ChapterId).HasName("PK__Manga_Ch__0893A34A72916779");

            entity.ToTable("Manga_Chapter");

            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.SeriesId).HasColumnName("SeriesID");
            entity.Property(e => e.Title).HasMaxLength(255);

            entity.HasOne(d => d.Series).WithMany(p => p.MangaChapters)
                .HasForeignKey(d => d.SeriesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manga_Cha__Serie__32E0915F");
        });

        modelBuilder.Entity<MangaSeries>(entity =>
        {
            entity.HasKey(e => e.SeriesId).HasName("PK__Manga_Se__F3A1C101BB61B770");

            entity.ToTable("Manga_Series");

            entity.Property(e => e.SeriesId).HasColumnName("SeriesID");
            entity.Property(e => e.AuthorId).HasColumnName("AuthorID");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(255);

            entity.HasOne(d => d.Author).WithMany(p => p.MangaSeries)
                .HasForeignKey(d => d.AuthorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manga_Ser__Autho__300424B4");

            entity.HasMany(d => d.Categories).WithMany(p => p.Series)
                .UsingEntity<Dictionary<string, object>>(
                    "SeriesCategoryMap",
                    r => r.HasOne<CategoryMaster>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Series_Ca__Categ__571DF1D5"),
                    l => l.HasOne<MangaSeries>().WithMany()
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__Series_Ca__Serie__5629CD9C"),
                    j =>
                    {
                        j.HasKey("SeriesId", "CategoryId").HasName("PK__Series_C__523152A31AF8352A");
                        j.ToTable("Series_Category_Map");
                        j.IndexerProperty<int>("SeriesId").HasColumnName("SeriesID");
                        j.IndexerProperty<int>("CategoryId").HasColumnName("CategoryID");
                    });
        });

        modelBuilder.Entity<MangaStatistic>(entity =>
        {
            entity.HasKey(e => e.StatId).HasName("PK__Manga_St__3A162D1E275B1C84");

            entity.ToTable("Manga_Statistics");

            entity.HasIndex(e => e.SeriesId, "UQ__Manga_St__F3A1C10056A6CE74").IsUnique();

            entity.Property(e => e.StatId).HasColumnName("StatID");
            entity.Property(e => e.RatingScore)
                .HasDefaultValue(0m)
                .HasColumnType("decimal(3, 2)");
            entity.Property(e => e.SeriesId).HasColumnName("SeriesID");
            entity.Property(e => e.TotalViews).HasDefaultValue(0L);

            entity.HasOne(d => d.Series).WithOne(p => p.MangaStatistic)
                .HasForeignKey<MangaStatistic>(d => d.SeriesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manga_Sta__Serie__38996AB5");
        });

        modelBuilder.Entity<ManuscriptAnnotation>(entity =>
        {
            entity.HasKey(e => e.AnnotationId).HasName("PK__Manuscri__FC2AC5A3C7E8FAC1");

            entity.ToTable("Manuscript_Annotation");

            entity.Property(e => e.AnnotationId).HasColumnName("AnnotationID");
            entity.Property(e => e.EditorId).HasColumnName("EditorID");
            entity.Property(e => e.PageId).HasColumnName("PageID");

            entity.HasOne(d => d.Editor).WithMany(p => p.ManuscriptAnnotations)
                .HasForeignKey(d => d.EditorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manuscrip__Edito__440B1D61");

            entity.HasOne(d => d.Page).WithMany(p => p.ManuscriptAnnotations)
                .HasForeignKey(d => d.PageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manuscrip__PageI__4316F928");
        });

        modelBuilder.Entity<ManuscriptPage>(entity =>
        {
            entity.HasKey(e => e.PageId).HasName("PK__Manuscri__C565B124B996A2D9");

            entity.ToTable("Manuscript_Page");

            entity.Property(e => e.PageId).HasColumnName("PageID");
            entity.Property(e => e.ChapterId).HasColumnName("ChapterID");
            entity.Property(e => e.CurrentStatus)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.Chapter).WithMany(p => p.ManuscriptPages)
                .HasForeignKey(d => d.ChapterId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manuscrip__Chapt__3B75D760");
        });

        modelBuilder.Entity<ManuscriptVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("PK__Manuscri__16C6402FA9303EFD");

            entity.ToTable("Manuscript_Version");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.AssetUrl)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("AssetURL");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PageId).HasColumnName("PageID");
            entity.Property(e => e.VersionNumber).HasDefaultValue(1);

            entity.HasOne(d => d.Page).WithMany(p => p.ManuscriptVersions)
                .HasForeignKey(d => d.PageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Manuscrip__PageI__403A8C7D");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE3A9BDBA5F3");

            entity.ToTable("Role");

            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<RoyaltyPaymentThinhPh>(entity =>
        {
            entity.HasKey(e => e.PaymentIdThinhPh).HasName("PK__Royalty___9B556A587DA59288");

            entity.ToTable("Royalty_Payment_ThinhPH");

            entity.Property(e => e.PaymentIdThinhPh).HasColumnName("PaymentID_ThinhPH");
            entity.Property(e => e.Amount).HasColumnType("money");
            entity.Property(e => e.ContractIdThinhPh).HasColumnName("ContractID_ThinhPH");
            entity.Property(e => e.PaymentDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PaymentStatus)
                .HasMaxLength(20)
                .IsUnicode(false);

            entity.HasOne(d => d.ContractIdThinhPhNavigation).WithMany(p => p.RoyaltyPaymentThinhPhs)
                .HasForeignKey(d => d.ContractIdThinhPh)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Royalty_P__Contr__76969D2E");
        });

        modelBuilder.Entity<SeriesCollection>(entity =>
        {
            entity.HasKey(e => e.CollectionId).HasName("PK__Series_C__7DE6BC245B5B15B9");

            entity.ToTable("Series_Collection");

            entity.Property(e => e.CollectionId).HasColumnName("CollectionID");
            entity.Property(e => e.CollectionName).HasMaxLength(100);
            entity.Property(e => e.DisplayOrder).HasDefaultValue(0);
            entity.Property(e => e.SeriesId).HasColumnName("SeriesID");

            entity.HasOne(d => d.Series).WithMany(p => p.SeriesCollections)
                .HasForeignKey(d => d.SeriesId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Series_Co__Serie__5AEE82B9");
        });

        modelBuilder.Entity<SystemUserAccount>(entity =>
        {
            entity.HasKey(e => e.UserAccountId).HasName("PK__System_U__DA6C70BAB7BBDF3E");

            entity.ToTable("System_UserAccount");

            entity.HasIndex(e => e.UserName, "UQ__System_U__C9F28456820E928D").IsUnique();

            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");
            entity.Property(e => e.CreatedDate)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Email).HasMaxLength(150);
            entity.Property(e => e.FullName).HasMaxLength(100);
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Role).WithMany(p => p.SystemUserAccounts)
                .HasForeignKey(d => d.RoleId)
                .HasConstraintName("FK__System_Us__RoleI__29572725");
        });

        modelBuilder.Entity<TaskAssignment>(entity =>
        {
            entity.HasKey(e => e.TaskId).HasName("PK__Task_Ass__7C6949D1BF01D65D");

            entity.ToTable("Task_Assignment");

            entity.Property(e => e.TaskId).HasColumnName("TaskID");
            entity.Property(e => e.AssigneeId).HasColumnName("AssigneeID");
            entity.Property(e => e.Deadline).HasColumnType("datetime");
            entity.Property(e => e.PageId).HasColumnName("PageID");
            entity.Property(e => e.TaskType)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Assignee).WithMany(p => p.TaskAssignments)
                .HasForeignKey(d => d.AssigneeId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Task_Assi__Assig__47DBAE45");

            entity.HasOne(d => d.Page).WithMany(p => p.TaskAssignments)
                .HasForeignKey(d => d.PageId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Task_Assi__PageI__46E78A0C");
        });

        modelBuilder.Entity<TaskReview>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Task_Rev__74BC79AEB43C4484");

            entity.ToTable("Task_Review");

            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.IsApproved).HasDefaultValue(false);
            entity.Property(e => e.ReviewerId).HasColumnName("ReviewerID");
            entity.Property(e => e.TaskId).HasColumnName("TaskID");

            entity.HasOne(d => d.Reviewer).WithMany(p => p.TaskReviews)
                .HasForeignKey(d => d.ReviewerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Task_Revi__Revie__5070F446");

            entity.HasOne(d => d.Task).WithMany(p => p.TaskReviews)
                .HasForeignKey(d => d.TaskId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Task_Revi__TaskI__4F7CD00D");
        });

        modelBuilder.Entity<TaskSubmission>(entity =>
        {
            entity.HasKey(e => e.SubmissionId).HasName("PK__Task_Sub__449EE105E6BC63EF");

            entity.ToTable("Task_Submission");

            entity.Property(e => e.SubmissionId).HasColumnName("SubmissionID");
            entity.Property(e => e.SubmissionUrl)
                .HasMaxLength(500)
                .IsUnicode(false)
                .HasColumnName("SubmissionURL");
            entity.Property(e => e.SubmittedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.TaskId).HasColumnName("TaskID");

            entity.HasOne(d => d.Task).WithMany(p => p.TaskSubmissions)
                .HasForeignKey(d => d.TaskId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Task_Subm__TaskI__4BAC3F29");
        });

        modelBuilder.Entity<UserActivityLog>(entity =>
        {
            entity.HasKey(e => e.LogId).HasName("PK__User_Act__5E5499A806CCA255");

            entity.ToTable("User_Activity_Log");

            entity.Property(e => e.LogId).HasColumnName("LogID");
            entity.Property(e => e.ActionType).HasMaxLength(50);
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserAccountId).HasColumnName("UserAccountID");

            entity.HasOne(d => d.UserAccount).WithMany(p => p.UserActivityLogs)
                .HasForeignKey(d => d.UserAccountId)
                .HasConstraintName("FK__User_Acti__UserA__2D27B809");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}