// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class MangaChapter
{
    public int ChapterId { get; set; }

    public int SeriesId { get; set; }

    public int ChapterNumber { get; set; }

    public string Title { get; set; }

    public virtual ICollection<ManuscriptPage> ManuscriptPages { get; set; } = new List<ManuscriptPage>();

    public virtual MangaSeries Series { get; set; }
}