// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class MangaSeries
{
    public int SeriesId { get; set; }

    public int AuthorId { get; set; }

    public string Title { get; set; }

    public string Status { get; set; }

    public virtual SystemUserAccount Author { get; set; }

    public virtual ICollection<ContractMasterThinhPh> ContractMasterThinhPhs { get; set; } = new List<ContractMasterThinhPh>();

    public virtual ICollection<MangaChapter> MangaChapters { get; set; } = new List<MangaChapter>();

    public virtual MangaStatistic MangaStatistic { get; set; }

    public virtual ICollection<SeriesCollection> SeriesCollections { get; set; } = new List<SeriesCollection>();

    public virtual ICollection<CategoryMaster> Categories { get; set; } = new List<CategoryMaster>();
}