// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class MangaStatistic
{
    public int StatId { get; set; }

    public int SeriesId { get; set; }

    public long? TotalViews { get; set; }

    public decimal? RatingScore { get; set; }

    public virtual MangaSeries Series { get; set; }
}