// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class ManuscriptVersion
{
    public int VersionId { get; set; }

    public int PageId { get; set; }

    public string AssetUrl { get; set; }

    public int? VersionNumber { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ManuscriptPage Page { get; set; }
}