// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class ManuscriptAnnotation
{
    public int AnnotationId { get; set; }

    public int PageId { get; set; }

    public int EditorId { get; set; }

    public string CommentContent { get; set; }

    public string CoordinateData { get; set; }

    public virtual SystemUserAccount Editor { get; set; }

    public virtual ManuscriptPage Page { get; set; }
}