// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class ManuscriptPage
{
    public int PageId { get; set; }

    public int ChapterId { get; set; }

    public int PageNumber { get; set; }

    public string CurrentStatus { get; set; }

    public virtual MangaChapter Chapter { get; set; }

    public virtual ICollection<ManuscriptAnnotation> ManuscriptAnnotations { get; set; } = new List<ManuscriptAnnotation>();

    public virtual ICollection<ManuscriptVersion> ManuscriptVersions { get; set; } = new List<ManuscriptVersion>();

    public virtual ICollection<TaskAssignment> TaskAssignments { get; set; } = new List<TaskAssignment>();
}