// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class RoyaltyPaymentThinhPh
{
    public int PaymentIdThinhPh { get; set; }

    public int ContractIdThinhPh { get; set; }

    public decimal Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentStatus { get; set; }

    public virtual ContractMasterThinhPh ContractIdThinhPhNavigation { get; set; }
}