// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class SeriesCollection
{
    public int CollectionId { get; set; }

    public int SeriesId { get; set; }

    public string CollectionName { get; set; }

    public int? DisplayOrder { get; set; }

    public virtual MangaSeries Series { get; set; }
}