// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class TaskSubmission
{
    public int SubmissionId { get; set; }

    public int TaskId { get; set; }

    public string SubmissionUrl { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public virtual TaskAssignment Task { get; set; }
}