// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class TaskReview
{
    public int ReviewId { get; set; }

    public int TaskId { get; set; }

    public int ReviewerId { get; set; }

    public bool? IsApproved { get; set; }

    public string Note { get; set; }

    public virtual SystemUserAccount Reviewer { get; set; }

    public virtual TaskAssignment Task { get; set; }
}