// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class TaskAssignment
{
    public int TaskId { get; set; }

    public int PageId { get; set; }

    public int AssigneeId { get; set; }

    public string TaskType { get; set; }

    public DateTime? Deadline { get; set; }

    public virtual SystemUserAccount Assignee { get; set; }

    public virtual ManuscriptPage Page { get; set; }

    public virtual ICollection<TaskReview> TaskReviews { get; set; } = new List<TaskReview>();

    public virtual ICollection<TaskSubmission> TaskSubmissions { get; set; } = new List<TaskSubmission>();
}