// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Manga.Entites.ThinhPH.Models;

public partial class UserActivityLog
{
    public int LogId { get; set; }

    public int? UserAccountId { get; set; }

    public string ActionType { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual SystemUserAccount UserAccount { get; set; }
}